github:
  token: '$GITHUB_TOKEN'

mongo:
    uri: "mongodb://localhost:27018"
    database: "github_data"

projects:
#  - name: 'flairNLP/fundus'
#    source_directory: 'src/fundus'
#    get_newest: False
#    ablation: False
#    models:
#      - class: LinearRegressionModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: LinearRegressionModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: MedianBaseModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: MedianBaseModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: RandomForestModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: RandomForestModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: GradientBoosting
#        feature_type: regression
#        split_strategy: by_file
#      - class: GradientBoosting
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: XGBoostModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: XGBoostModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: LightGBMModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: LightGBMModel
#        feature_type: regression
#        split_strategy: by_history
#
#  - name: 'khoj-ai/khoj'
#    source_directory: 'src'
#    get_newest: False
#    ablation: False
#    models:
#      - class: LightGBMModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: LightGBMModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: LinearRegressionModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: LinearRegressionModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: MedianBaseModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: MedianBaseModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: RandomForestModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: RandomForestModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: GradientBoosting
#        feature_type: regression
#        split_strategy: by_file
#      - class: GradientBoosting
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: XGBoostModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: XGBoostModel
#        feature_type: regression
#        split_strategy: by_history
#
#  - name: 'vuejs/core'
#    source_directory: 'packages'
#    get_newest: False
#    ablation: False
#    models:
#      - class: LinearRegressionModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: LinearRegressionModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: MedianBaseModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: MedianBaseModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: LightGBMModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: LightGBMModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: RandomForestModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: RandomForestModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: GradientBoosting
#        feature_type: regression
#        split_strategy: by_file
#      - class: GradientBoosting
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: XGBoostModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: XGBoostModel
#        feature_type: regression
#        split_strategy: by_history
#
#  - name: 'mozilla/addons-server'
#    source_directory: 'src/olympia'
#    get_newest: False
#    ablation: False
#    models:
#      - class: LinearRegressionModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: LinearRegressionModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: MedianBaseModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: MedianBaseModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: LightGBMModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: LightGBMModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: RandomForestModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: RandomForestModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: GradientBoosting
#        feature_type: regression
#        split_strategy: by_file
#      - class: GradientBoosting
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: XGBoostModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: XGBoostModel
#        feature_type: regression
#        split_strategy: by_history
#
#  - name: 'fastapi/fastapi'
#    source_directory: 'fastapi'
#    get_newest: False
#    ablation: False
#    models:
#      - class: LinearRegressionModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: LinearRegressionModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: MedianBaseModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: MedianBaseModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: LightGBMModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: LightGBMModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: RandomForestModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: RandomForestModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: GradientBoosting
#        feature_type: regression
#        split_strategy: by_file
#      - class: GradientBoosting
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: XGBoostModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: XGBoostModel
#        feature_type: regression
#        split_strategy: by_history
#
#  - name: 'pallets/flask'
#    source_directory: 'src/flask'
#    get_newest: False
#    ablation: False
#    models:
#      - class: LinearRegressionModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: LinearRegressionModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: MedianBaseModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: MedianBaseModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: LightGBMModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: LightGBMModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: RandomForestModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: RandomForestModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: GradientBoosting
#        feature_type: regression
#        split_strategy: by_file
#      - class: GradientBoosting
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: XGBoostModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: XGBoostModel
#        feature_type: regression
#        split_strategy: by_history
#
#  - name: 'keras-team/keras'
#    source_directory: 'keras'
#    get_newest: False
#    ablation: False
#    models:
#      - class: LinearRegressionModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: LinearRegressionModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: MedianBaseModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: MedianBaseModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: LightGBMModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: LightGBMModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: RandomForestModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: RandomForestModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: GradientBoosting
#        feature_type: regression
#        split_strategy: by_file
#      - class: GradientBoosting
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: XGBoostModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: XGBoostModel
#        feature_type: regression
#        split_strategy: by_history

  - name: 'tabler/tabler'
    source_directory: ''
    get_newest: False
    ablation: False
    models:
#      - class: LinearRegressionModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: LinearRegressionModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: MedianBaseModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: MedianBaseModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: LightGBMModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: LightGBMModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: RandomForestModel
#        feature_type: regression
#        split_strategy: by_file
      - class: RandomForestModel
        feature_type: regression
        split_strategy: by_history
#
#      - class: GradientBoosting
#        feature_type: regression
#        split_strategy: by_file
#      - class: GradientBoosting
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: XGBoostModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: XGBoostModel
#        feature_type: regression
#        split_strategy: by_history

#  - name: 'google/material-design-lite'
#    source_directory: 'src'
#    get_newest: False
#    ablation: False
#    models:
#      - class: LinearRegressionModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: LinearRegressionModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: MedianBaseModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: MedianBaseModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: LightGBMModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: LightGBMModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: RandomForestModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: RandomForestModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: GradientBoosting
#        feature_type: regression
#        split_strategy: by_file
#      - class: GradientBoosting
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: XGBoostModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: XGBoostModel
#        feature_type: regression
#        split_strategy: by_history
#
#  - name: 'google/gson'
#    source_directory: 'gson'
#    get_newest: False
#    ablation: False
#    models:
#      - class: LinearRegressionModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: LinearRegressionModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: MedianBaseModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: MedianBaseModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: LightGBMModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: LightGBMModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: RandomForestModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: RandomForestModel
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: GradientBoosting
#        feature_type: regression
#        split_strategy: by_file
#      - class: GradientBoosting
#        feature_type: regression
#        split_strategy: by_history
#
#      - class: XGBoostModel
#        feature_type: regression
#        split_strategy: by_file
#      - class: XGBoostModel
#        feature_type: regression
#        split_strategy: by_history
